name: coverage

on:
  push:
    branches-ignore:
      - 'docker'
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 04:00

jobs:
build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Debug]
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true   
        fetch-depth: 0

    - name: Create Build Environment
      run: |
        sudo apt update && sudo apt install git lcov libsdl2-dev libpng-dev libjpeg-dev libz-dev
        cmake -E make_directory ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DENABLE_COVERAGE=ON \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}} -- -j $(nproc)

    - name: lcov prepare
      working-directory: ${{runner.workspace}}
      run : |
        ./.github/tools/lnx/lcov_init.sh ${{runner.workspace}}/build ${{runner.workspace}}

    - name: Tests
      working-directory: ${{runner.workspace}}/build
      run: ctest ${{matrix.build_type}}

    - name: lcov creation
      working-directory: ${{runner.workspace}}
      run : |
        ./.github/tools/lnx/lcov_gen.sh ${{runner.workspace}}/build ${{runner.workspace}}

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{runner.workspace}}/cov_filter.info

