name: coverage

on:
  push:
    branches-ignore:
      - 'docker'
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 04:00

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        build_type: [Debug]
        os: [ubuntu-20.04]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true   
        fetch-depth: 0

    - name: Create Build Environment
      run: |
        sudo apt update && sudo apt install git lcov libsdl2-dev libpng-dev libjpeg-dev libz-dev libmpg123-dev
        cmake -E make_directory ${{runner.workspace}}/build
        ln -sf $GITHUB_WORKSPACE/projects/mtg/Res ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DDISABLE_UI=ON \
              -DENABLE_COVERAGE=ON \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}} -- -j $(nproc)

    - name: lcov prepare
      working-directory: ${{runner.workspace}}
      run : |
        lcov --zerocounters --directory ${{runner.workspace}}/build
        lcov --capture --initial --directory . --output-file cov_base.info

    - name: Start Unittests
      working-directory: ${{runner.workspace}}/build
      run: ctest ${{matrix.build_type}}

    - name: Start Testsuite
      working-directory: ${{runner.workspace}}/build
      run : ./projects/mtg/tests/testsuite/woth_testsuite

    - name: lcov creation
      working-directory: ${{runner.workspace}}
      run : |
        lcov --capture --directory . --output-file cov.info
        lcov --add-tracefile ./cov_base.info --add-tracefile ./cov.info --output-file cov_total.info
        lcov --remove ./cov_total.info '/usr/include/*' '/usr/lib/*' '*/wtest/*' '*/extern/*' '*/tests/*' '*/playground/*' -o cov_filter.info

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: ${{runner.workspace}}/cov_filter.info

