name: linux

on:
  push:
    branches-ignore:
      - 'docker'
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 04:00

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-4.8, g++-10, clang++-9]
        build_type: [Debug, Release]
        std: [14, 17]
        os: [ubuntu-20.04]
        include:
          - cxx: g++-10
            install: sudo apt install libsdl2-dev libz-dev
          - cxx: clang++-11
            cxxflags: -stdlib=libc++
            install: sudo apt install libc++-11-dev libc++abi-11-dev libsdl2-dev libz-dev


    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build
    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              $GITHUB_WORKSPACE
    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}} -- -j $(nproc)
