name: linux

on:
  push:
    branches-ignore:
      - 'docker'
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 04:00

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        cxx: [g++-10, clang++-11]
        build_type: [Debug, Release]
        std: [20]
        os: [ubuntu-20.04]
        include:
          - cxx: g++-10
            install: sudo apt update && sudo apt install git libsdl2-dev libpng-dev libjpeg-dev libfreetype-dev libz-dev
          - cxx: clang++-11
            cxxflags: -stdlib=libc++
            install: sudo apt update && sudo apt install git libc++-11-dev libc++abi-11-dev libsdl2-dev libpng-dev libjpeg-dev libfreetype-dev libz-dev

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true   
        fetch-depth: 0

    - name: Create Build Environment
      run: |
        ${{matrix.install}}
        cmake -E make_directory ${{runner.workspace}}/build
        ln -sf $GITHUB_WORKSPACE/projects/mtg/Res ${{runner.workspace}}/build

    - name: Configure
      working-directory: ${{runner.workspace}}/build
      env:
        CXX: ${{matrix.cxx}}
        CXXFLAGS: ${{matrix.cxxflags}}
      run: |
        cmake -DCMAKE_BUILD_TYPE=${{matrix.build_type}} \
              -DCMAKE_CXX_STANDARD=${{matrix.std}} \
              $GITHUB_WORKSPACE

    - name: Build
      working-directory: ${{runner.workspace}}/build
      run: cmake --build . --config ${{matrix.build_type}} -- -j $(nproc)

    - name: Run Unittests
      working-directory: ${{runner.workspace}}/build
      run: ctest ${{matrix.build_type}}

    - name: Run Testsuite
      if: ${{ matrix.build_type == 'Debug' }}
      working-directory: ${{runner.workspace}}/build
      run: ./projects/mtg/tests/testsuite/woth_testsuite
