name: android

on:
  push:
    branches-ignore:
      - 'docker'
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 04:00

jobs:
  native_build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: [Release, Debug]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: build
      uses: docker://saschpe/android-ndk:latest
      with:
        args: /bin/sh -c ".github/tools/ndk/build.sh" ${{ matrix.config }}
