name: psp

on:
  push:
    branches-ignore:
      - 'docker'
  schedule:
    - cron: '0 4 * * 0' # Weekly on Sundays at 04:00

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config: [Release, Debug, MinSizeRel]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true    
        fetch-depth: 0


    - name: build
      uses: docker://zie87/wth_woth_pspdev:main
      with:
        args: /bin/sh -c ".github/tools/psp/build.sh ${{ matrix.config }}"

    - name: upload package
      uses: actions/upload-artifact@v2
      with:
        name: psp_${{ matrix.config }}
        path: build_psp/wth_woth_*_psp.zip
